function [funftI,funftII,funftIII,funftIV,funftV,funftVI]=...
    ftr_test(funfI,funfII,funfIII,funfIV,funfV,funfVI,n,nn)
[funftI,funftII,funftIII,funftIV,funftV,funftVI]=...
    ftr74(funfI,funfII,funfIII,funfIV,funfV,funfVI,n,nn);
end
